HR-OxCode/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HR_OxCode.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HR-OxCode/Controllers/LettersController.cs
using HR_OxCode.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HR_OxCode.Controllers
{
    public class LettersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LettersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Lettersindex()
        {
            
            return View(_context.Letters.ToList());
        }
    }
}

HR-OxCode/Controllers/PayrollController.cs
using HR_OxCode.Data;
using HR_OxCode.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HR_OxCode.Controllers
{
    public class PayrollController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PayrollController(ApplicationDbContext context)
        {
            _context = context;

            //ApplicationDbContext db = new ApplicationDbContext();
        }

        //Here
        public IActionResult Index()
        {
            var displayData = _context.Payrolles.ToList();
            return View(displayData);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payroll);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(payroll);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var GetpayrollDetails = await _context.Payrolles.FindAsync(id);
            return View(GetpayrollDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                _context.Update(payroll);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(payroll);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var GetpayrollDetails = await _context.Payrolles.FindAsync(id);
            return View(GetpayrollDetails);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var GetpayrollDetails = await _context.Payrolles.FindAsync(id);
            return View(GetpayrollDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var GetpayrollDetails = await _context.Payrolles.FindAsync(id);
            _context.Payrolles.Remove(GetpayrollDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        //----------------------------------------------------------------------------------------
        //OvertimeManagement : 
        public IActionResult Overyimeindex()
        {
            var displayData = _context.overtimes.ToList();
            return View(displayData);
        }
        public IActionResult CreateOveryime()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateOveryime(Overtime overtime)
        {
            if (ModelState.IsValid)
            {
                _context.Add(overtime);
                await _context.SaveChangesAsync();
                return RedirectToAction("Overyimeindex");
            }
            return View(overtime);
        }

        public async Task<IActionResult> EditOveryime(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Overyimeindex");
            }

            var GetOvertimeDetails = await _context.overtimes.FindAsync(id);
            return View(GetOvertimeDetails);
        }

        [HttpPost]
        public async Task<IActionResult> EditOveryime(Overtime overtime)
        {
            if (ModelState.IsValid)
            {
                _context.Update(overtime);
                await _context.SaveChangesAsync();
                return RedirectToAction("Overyimeindex");
            }
            return View(overtime);
        }

        public async Task<IActionResult> DetailsOveryime(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Overyimeindex");
            }

            var GetOvertimeDetails = await _context.overtimes.FindAsync(id);
            return View(GetOvertimeDetails);
        }

        public async Task<IActionResult> DeleteOveryime(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Overyimeindex");
            }

            var GetOvertimeDetails = await _context.overtimes.FindAsync(id);
            return View(GetOvertimeDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteOveryime(int id)
        {
            var GetOvertimeDetails = await _context.overtimes.FindAsync(id);
            _context.overtimes.Remove(GetOvertimeDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction("Overyimeindex");
        }

        //----------------------------------------------------------------------------------------
        //LoansManagement : 
        public IActionResult Loansindex()
        {
            var displayData = _context.loansManagements.ToList();
            return View(displayData);
        }

        public IActionResult CreateLoans()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateLoans(LoansManagement loansManagement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loansManagement);
                await _context.SaveChangesAsync();
                return RedirectToAction("Loansindex");
            }
            return View(loansManagement);
        }

        public async Task<IActionResult> EditLoans(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Loansindex");
            }

            var GetLoansDetails = await _context.loansManagements.FindAsync(id);
            return View(GetLoansDetails);
        }

        [HttpPost]
        public async Task<IActionResult> EditLoans(LoansManagement loansManagement)
        {
            if (ModelState.IsValid)
            {
                _context.Update(loansManagement);
                await _context.SaveChangesAsync();
                return RedirectToAction("Loansindex");
            }
            return View(loansManagement);
        }

        public async Task<IActionResult> DetailsLoans(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Loansindex");
            }

            var GetLoansDetails = await _context.loansManagements.FindAsync(id);
            return View(GetLoansDetails);
        }

        public async Task<IActionResult> DeleteLoans(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Loansindex");
            }

            var GetLoansDetails = await _context.loansManagements.FindAsync(id);
            return View(GetLoansDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteLoans(int id)
        {
            var GetLoansDetails = await _context.loansManagements.FindAsync(id);
            _context.loansManagements.Remove(GetLoansDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction("Loansindex");
        }

        //-------------------------------------------------------------------------------------------
        //PayLoans : 
        public IActionResult PayLoansindex()
        {

            //PayLoans payLoans= _context.payLoans.ToList();
            //var displayData = _context.payLoans.ToList();
            //Convert.ToString(displayData);
            return View(_context.payLoans.ToList());
        }

        public IActionResult CreatePayLoans()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePayLoans(PayLoans payLoans)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payLoans);
                await _context.SaveChangesAsync();
                return RedirectToAction("PayLoansindex");
            }
            return View(payLoans);
        }

        public async Task<IActionResult> EditPayLoans(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("PayLoansindex");
            }

            var GetPayDetails = await _context.payLoans.FindAsync(id);
            return View(GetPayDetails);
        }

        [HttpPost]
        public async Task<IActionResult> EditPayLoans(PayLoans payLoans)
        {
            if (ModelState.IsValid)
            {
                _context.Update(payLoans);
                await _context.SaveChangesAsync();
                return RedirectToAction("PayLoansindex");
            }
            return View(payLoans);
        }

        public async Task<IActionResult> DetailsPayLoans(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("PayLoansindex");
            }

            var GetPayDetails = await _context.payLoans.FindAsync(id);
            return View(GetPayDetails);
        }

        public async Task<IActionResult> DeletePayLoans(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("PayLoansindex");
            }

            var GetPayDetails = await _context.payLoans.FindAsync(id);
            return View(GetPayDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePayLoans(int id)
        {
            var GetPayDetails = await _context.payLoans.FindAsync(id);
            _context.payLoans.Remove(GetPayDetails);
            await _context.SaveChangesAsync();

HR-OxCode/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HR_OxCode.Controllers
{
    public class ReportsController : Controller
    {
        public IActionResult Reports()
        {
            return View();
        }

        public IActionResult Reports2()
        {
            return View();
        }

    }
}

HR-OxCode/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HR_OxCode</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">HR_OxCode</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="active nav-item"><a href="#" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                <li class="nav-item"><a href="#contact" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>

</html>

HR-OxCode/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR_OxCode</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    @*//BeginReport

    @Html.DevExpress().GetStyleSheets(
    
       new StyleSheet { ExtensionSuite = ExtensionSuite.Report}
    
    )
    @Html.DevExpress().GetScripts(


      new Script { ExtensionSuite = ExtensionSuite.Report}

    )

    <link href="@Uri.Content("~/Content/site.css") rel= "stylesheet" text="text/css">


    //EndReport*@

</head>
<body>

    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR_OxCode</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@

    <div>
        <h3> The Logo Of Webside </h3>
        
    </div>

    <div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Components</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Custom Components:</h6>
                    <a class="collapse-item" asp-controller="StaffProfile" asp-action="Index">StaffProfile</a>
                    <a class="collapse-item" asp-controller="Payroll" asp-action="Index">Payroll</a>
                    <a class="collapse-item" asp-controller="Letters" asp-action="Lettersindex">Letters</a>
                    <a class="collapse-item" asp-controller="contracts" asp-action="contracts">Contracts</a>
                    <a class="collapse-item" asp-controller="settings" asp-action="settings">Settings</a>
                    <a class="collapse-item" asp-controller="Apprasial" asp-action="Apprasial">Apprasial</a>
                    <a class="collapse-item" asp-controller="Airticket" asp-action="Airticket">AirTicket&GovernExpenses</a>
                    <a class="collapse-item" asp-controller="joboffers" asp-action="joboffers">JobOffers</a>
                    <a class="collapse-item" asp-controller="Reports" asp-action="Reports">Reports</a>
                    <a class="collapse-item" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                    <a class="collapse-item" href="cards.html">Cards</a>
                </div>
            </div>
        </li>


    </div>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HR_OxCode - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>