HR-OxCode/Controllers/settingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HR_OxCode.Data;
using HR_OxCode.Models;

namespace HR_OxCode.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SettingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Settings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Settings.ToListAsync());
        }

        // GET: Settings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settings = await _context.Settings
                .FirstOrDefaultAsync(m => m.id == id);
            if (settings == null)
            {
                return NotFound();
            }

            return View(settings);
        }

        // GET: Settings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Settings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,DepartmentAr,DepartmentEn,jobtitle,NationalityAr,NationalityEn,BankName")] Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(settings);
        }

        // GET: Settings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settings = await _context.Settings.FindAsync(id);
            if (settings == null)
            {
                return NotFound();
            }
            return View(settings);
        }

        // POST: Settings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,DepartmentAr,DepartmentEn,jobtitle,NationalityAr,NationalityEn,BankName")] Settings settings)
        {
            if (id != settings.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(settings);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SettingsExists(settings.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(settings);
        }

        // GET: Settings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settings = await _context.Settings
                .FirstOrDefaultAsync(m => m.id == id);
            if (settings == null)
            {
                return NotFound();
            }

            return View(settings);
        }

        // POST: Settings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var settings = await _context.Settings.FindAsync(id);
            _context.Settings.Remove(settings);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SettingsExists(int id)
        {
            return _context.Settings.Any(e => e.id == id);
        }
        //------------------------------------------------------------------------------------
        //jobTitle : 
        public IActionResult Jobtitleindex()
        {
            var displayData = _context.Settings.ToList();
            return View(displayData);
        }

        public IActionResult CreateJobtitle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateJobtitle(Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction("Jobtitleindex");
            }
            return View(settings);
        }

        public async Task<IActionResult> EditJobtitle(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Jobtitleindex");
            }

            var GetLoansDetails = await _context.Settings.FindAsync(id);
            return View(GetLoansDetails);
        }

        [HttpPost]
        public async Task<IActionResult> EditJobtitle(Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Update(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction("Jobtitleindex");
            }
            return View(settings);
        }

        public async Task<IActionResult> DetailsJobtitle(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Jobtitleindex");
            }

            var GetLoansDetails = await _context.Settings.FindAsync(id);
            return View(GetLoansDetails);
        }

        public async Task<IActionResult> DeleteJobtitle(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Jobtitleindex");
            }

            var GetLoansDetails = await _context.Settings.FindAsync(id);
            return View(GetLoansDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteJobtitle(int id)
        {
            var GetLoansDetails = await _context.Settings.FindAsync(id);
            _context.Settings.Remove(GetLoansDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction("Jobtitleindex");
        }
        //--------------------------------------------------------------------------------------
        //Nationality : 

        public IActionResult Nationaltyindex()
        {
            var displayData = _context.Settings.ToList();
            return View(displayData);
        }

        public IActionResult CreateNationality()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNationality(Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction("Nationaltyindex");
            }
            return View(settings);
        }

        public async Task<IActionResult> EditNationality(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Nationaltyindex");
            }

            var GetLoansDetails = await _context.Settings.FindAsync(id);
            return View(GetLoansDetails);
        }

        [HttpPost]
        public async Task<IActionResult> EditNationality(Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Update(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction("Nationaltyindex");
            }
            return View(settings);
        }

        public async Task<IActionResult> DetailsNationality(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Nationaltyindex");
            }

            var GetLoansDetails = await _context.Settings.FindAsync(id);
            return View(GetLoansDetails);
        }

        public async Task<IActionResult> DeleteNationality(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Nationaltyindex");
            }

            var GetLoansDetails = await _context.Settings.FindAsync(id);
            return View(GetLoansDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteNationality(int id)
        {
            var GetLoansDetails = await _context.Settings.FindAsync(id);
            _context.Settings.Remove(GetLoansDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction("Nationaltyindex");
        }
        //---------------------------------------------------------------------------------------
        //BankNAme :

        public IActionResult BankNameindex()
        {
            var displayData = _context.Settings.ToList();
            return View(displayData);
        }

        public IActionResult CreateBank()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBank(Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction("BankNameindex");
            }

HR-OxCode/Views/settings/BankNameindex.cshtml
@model IEnumerable<HR_OxCode.Models.Settings>

@{
    ViewData["Title"] = "BankNameindex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>BankNameindex</h1>

<p>
    <a asp-action="CreateBank">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.DepartmentAr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.jobtitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NationalityAr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NationalityEn)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.BankName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.DepartmentAr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentEn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.jobtitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NationalityAr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NationalityEn)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.BankName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

HR-OxCode/Views/settings/CreateBank.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "CreateBank";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>CreateBank</h1>

<h4>Settings</h4>
<hr />
<div class="row m-5">
    <div class="col-md-4">
        <form asp-action="CreateBank">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="DepartmentAr" class="control-label"></label>
                <input asp-for="DepartmentAr" class="form-control" />
                <span asp-validation-for="DepartmentAr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentEn" class="control-label"></label>
                <input asp-for="DepartmentEn" class="form-control" />
                <span asp-validation-for="DepartmentEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="jobtitle" class="control-label"></label>
                <input asp-for="jobtitle" class="form-control" />
                <span asp-validation-for="jobtitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NationalityAr" class="control-label"></label>
                <input asp-for="NationalityAr" class="form-control" />
                <span asp-validation-for="NationalityAr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NationalityEn" class="control-label"></label>
                <input asp-for="NationalityEn" class="form-control" />
                <span asp-validation-for="NationalityEn" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="m-5">
    <a asp-action="Index">Back to List</a>
</div>

HR-OxCode/Views/settings/CreateJobtitle.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "CreateJobtitle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>CreateJobtitle</h1>

<h4>Settings</h4>
<hr />
<div class="row  m-5">
    <div class="col-md-4">
        <form asp-action="CreateJobtitle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="DepartmentAr" class="control-label"></label>
                <input asp-for="DepartmentAr" class="form-control" />
                <span asp-validation-for="DepartmentAr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentEn" class="control-label"></label>
                <input asp-for="DepartmentEn" class="form-control" />
                <span asp-validation-for="DepartmentEn" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="jobtitle" class="control-label"></label>
                <input asp-for="jobtitle" class="form-control" />
                <span asp-validation-for="jobtitle" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="NationalityAr" class="control-label"></label>
                <input asp-for="NationalityAr" class="form-control" />
                <span asp-validation-for="NationalityAr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NationalityEn" class="control-label"></label>
                <input asp-for="NationalityEn" class="form-control" />
                <span asp-validation-for="NationalityEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="m-5">
    <a asp-action="Index">Back to List</a>
</div>

HR-OxCode/Views/settings/CreateNationality.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "CreateNationality";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>CreateNationality</h1>

<h4>Settings</h4>
<hr />
<div class="row m-5">
    <div class="col-md-4">
        <form asp-action="CreateNationality">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="DepartmentAr" class="control-label"></label>
                <input asp-for="DepartmentAr" class="form-control" />
                <span asp-validation-for="DepartmentAr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentEn" class="control-label"></label>
                <input asp-for="DepartmentEn" class="form-control" />
                <span asp-validation-for="DepartmentEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="jobtitle" class="control-label"></label>
                <input asp-for="jobtitle" class="form-control" />
                <span asp-validation-for="jobtitle" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="NationalityAr" class="control-label"></label>
                <input asp-for="NationalityAr" class="form-control" />
                <span asp-validation-for="NationalityAr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NationalityEn" class="control-label"></label>
                <input asp-for="NationalityEn" class="form-control" />
                <span asp-validation-for="NationalityEn" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="m-5">
    <a asp-action="Index">Back to List</a>
</div>

HR-OxCode/Views/settings/Delete.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Settings</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jobtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jobtitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HR-OxCode/Views/settings/DeleteJobtitle.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "DeleteJobtitle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DeleteJobtitle</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Settings</h4>
    <hr />
    <dl class="row m-5">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentEn)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jobtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jobtitle)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankName)
        </dd>*@
    </dl>
    
    <form asp-action="DeleteJobtitle">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HR-OxCode/Views/settings/Details.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Settings</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jobtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jobtitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HR-OxCode/Views/settings/DetailsBank.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "DetailsBank";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DetailsBank</h1>

<div class="m-5">
    <h4>Settings</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jobtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jobtitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityEn)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankName)
        </dd>
    </dl>
</div>
<div class="m-5">
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HR-OxCode/Views/settings/DetailsJobtitle.cshtml
@model HR_OxCode.Models.Settings

@{
    ViewData["Title"] = "DetailsJobtitle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DetailsJobtitle</h1>

<div>
    <h4>Settings</h4>
    <hr />
    <dl class="row m-5">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentEn)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jobtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jobtitle)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityAr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityAr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankName)
        </dd>*@
    </dl>
</div>
<div class="m-5">
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HR-OxCode/Views/settings/Index.cshtml
@model IEnumerable<HR_OxCode.Models.Settings>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Link</a>
    </li>
  
    <li class="nav-item">
        <a class="nav-link" asp-controller="Settings" asp-action="Loansindex">Jobtitle</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Settings" asp-action="PayLoansindex">Nationality</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Settings" asp-action="Deductindex">BankName</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
    </li>

</ul>



<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentAr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentEn)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.jobtitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NationalityAr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NationalityEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BankName)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentAr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentEn)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.jobtitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NationalityAr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NationalityEn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BankName)
            </td>*@
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

HR-OxCode/Views/settings/settings.cshtml
@{
    ViewData["Title"] = "settings";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>settings</h1>